apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no

resources:
    - ../../../base

labels:
    -   pairs:
            app.kubernetes.io/instance: fint-flyt-egrunnerverv-okonomi_fintlabs_no
            fintlabs.no/org-id: fintlabs.no

patches:
    -   patch: |-
            -   op: replace
                path: "/spec/ingress/basePath"
                value: "/beta/api"

            -   op: replace
                path: "/spec/url/basePath"
                value: "/beta"

            -   op: replace
                path: "/spec/observability/metrics/path"
                value: "/beta/actuator/prometheus"

            -   op: replace
                path: "/spec/probes/readiness/path"
                value: "/beta/actuator/health"
            -   op: replace
                path: "/spec/probes/liveness/path"
                value: "/beta/actuator/health"
            -   op: replace
                path: "/spec/probes/startup/path"
                value: "/beta/actuator/health"

            -   op: add
                path: "/spec/env/-"
                value:
                    name: ADAPTER_ADAPTERS_SERVICENOW_BASE_URL
                    value: https://vigoikstest.service-now.com/api/now/table

        target:
            kind: Application
            name: fint-flyt-egrunnerverv-okonomi

    -   patch: |-
            -   op: replace
                path: "/spec/itemPath"
                value: "vaults/aks-beta-vault/items/novari-flyt-egrunnerverv-gateway-out"

        target:
            kind: OnePasswordItem
            name: novari-flyt-egrunnerverv-dispatch-oauth2-client

    -   patch: |-
            -   op: replace
                path: "/spec/itemPath"
                value: "vaults/aks-beta-vault/items/egrunnerverv-okonomi-visma-oauth2-client"

        target:
            kind: OnePasswordItem
            name: egrunnerverv-okonomi-visma-oauth2-client
