spring:
    application:
        name: flyt.egrunnerverv.okonomi

    threads:
        virtual:
            enabled: true

    output:
        ansi:
            enabled: always

adapter:
    supplier:
        by-tenant:
            novari-no: visma

    adapters:
        visma:
            company:
                by-tenant:
                    novari-no: 29

            retry:
                max-attempts: 5
                initial-interval-ms: 500

        servicenow:
            retry:
                max-attempts: 5
                initial-interval-ms: 500
