spring:
  application:
    name: flyt.egrunnerverv.okonomi

  security:
      oauth2:
          client:
              registration:
                  visma:
                      authorization-grant-type: client_credentials
                      client-id: BYTT_MEG_UT
                      client-secret: BYTT_MEG_UT
              provider:
                  visma:
                      token-uri: https://integrationtest.enterprise-stag.visma.no/authz/api/oauth/token/

  threads:
    virtual:
      enabled: true

novari:
  adapter:
      supplier:
          by-tenant:
              novari-no: visma

visma:
    base-url: ""
    legacy-auth: ""
    oauth:
        client-id: ""
        client-secret: ""
        token-url: ""

    company:
      by-tenant:
        novari-no: 29

logging:
    structured:
        format:
            console: ecs
