fint:
    application-id: fint-flyt-egrunnerverv-okonomi
    org-id: novari.no

spring:
    application:
        name: flyt.egrunnerverv.okonomi

    threads:
        virtual:
            enabled: true

    output:
        ansi:
            enabled: always

    profiles:
        include:
            - flyt-web-resource-server
            - flyt-kafka

adapter:
    supplier:
        by-org-no:
            999999999: novari-no
#            930580783: afk-no
#            921707134: agderfk-no
#            930580260: bfk-no
#            830090282: ffk-no
#            920717152: innlandetfylke-no
#            944183779: mfk-no
#            964982953: nfk-no
#            930580694: ofk-no
#            971045698: rogfk-no
#            929882989: telemarkfylke-no
#            930068128: tromsfylke-no
#            817920632: trondelagfylke-no
#            929882385: vestfoldfylke-no
#            821311632: vfk-no

        by-tenant:
            novari-no: visma

    adapters:
        visma:
            company:
                by-tenant:
                    novari-no: 29

            retry:
                max-attempts: 5
                initial-interval-ms: 500

        servicenow:
            retry:
                max-attempts: 5
                initial-interval-ms: 500
