spring:
    security:
        oauth2:
            client:
                registration:
                    visma:
                        client-id: "client-id"
                        client-secret: "client-secret"
                        authorization-grant-type: client_credentials

                    servicenow:
                        client-id: "client-id"
                        client-secret: "client-secret"
                        authorization-grant-type: password

                provider:
                  visma:
                      token-uri: "https://localhost"

                  servicenow:
                      token-uri: "https://localhost"

adapter:
    adapters:
        visma:
            registration-id: "local-visma"
            base-url: ""
            legacy-auth: ""

        servicenow:
            registration-id: "local-servicenow"
            base-url: ""
            oauth2:
                username: "username"
                password: "password"
