apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no

resources:
    - ../../../base

labels:
    -   pairs:
            app.kubernetes.io/instance: fint-flyt-egrunnerverv-okonomi_fintlabs_no
            fintlabs.no/org-id: fintlabs.no

patches:
    -   patch: |-
            -   op: replace
                path: "/spec/itemPath"
                value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-gateway-out"

        target:
            kind: OnePasswordItem
            name: novari-flyt-egrunnerverv-dispatch-oauth2-client

    -   patch: |-
            -   op: replace
                path: "/spec/itemPath"
                value: "vaults/aks-beta-vault/items/egrunnerverv-okonomi-visma-oauth2-client"

        target:
            kind: OnePasswordItem
            name: novari-flyt-egrunnerverv-dispatch-oauth2-client
