apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - flais.yaml
    - hpa.yaml
    - oauth2-egrunnerverv-client.yaml
    - egrunnerverv-dispatch-onepassword.yaml
    - visma-onepassword.yaml
